### PR TITLE
Basic album support

### PR DESCRIPTION
**Pull request by amoliski**

### CODE REVIEW

**Comment by amoliski** [comment]
Ah, crap, it's still got my other changes from my main branch messup from earlier. Sorry about that, I'll get it right next time.

By the way, my javascript is pretty rusty, so my feelings won't be hurt at all if these pull requests are rejected.

**Comment by honestbleeps** [comment]
new PRs coming soon? :-)

**Comment by amoliski** [comment]
Yeah, I think I've got the branch/work/push/submit request thing worked out- sorry about all the notifications :|

**Comment by honestbleeps** [comment]
no need to apologize, you're learning the process and I just appreciate
that you're working to help!

**Pull request closed without merging**
