### PR TITLE
Thumbnail and images with PHP get var support

### PR DESCRIPTION
**Pull request by amoliski**
Not sure why github isn't letting me submit two separate pull requests for two separate commits, any advice would be appreciated.

First one makes it so you can hover over a thumbnail on reddit to open the hoverzoom window

Second one adds support for images that end with "?*" PHP get vars, for example 
http://www.reddit.com/r/PerfectTiming/comments/1zfvxy/after_a_pilots_first_combat_mission/
links to the image:
http://i.imgur.com/HlfzA7S.jpg?1

Previously, the ?1 would have prevented a regex match.

### CODE REVIEW

**Comment by amoliski** [comment]
Yeah, github is adding anything I push to my repo to this pull request- I hope you have a way to approve/deny changes one at a time. I have a nagging feeling that I am using git wrong- I've never tried to submit a pull request for more than a single change in a public repo.

**Comment by hailwood** [comment]
Switch branches. Git checkout -b new_branch

Ideally you should have done that before this pull request and done a pull request from that.  Until this pull request is merged anything pushed to your master branch will be added to this pr

**Comment by hailwood** [comment]
So for each feature your ideal work flow would be:

Make sure you are on master

```
Git checkout -b feature-describe-your-feature
#e.g git checkout feature-getvar-support
# do your work
#add and commit
git push origin feature-getvar-support
#submit your pr
git checkout master
#start again
```

Something to note is that each pr should build off master _not_ one of your existing pr branches

**Comment by amoliski** [comment]
Ah, that makes sense, thank you!

**Pull request closed without merging**
